name: travel_hour
description: Vetores Vertentes

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.0.5+30

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
  
  audioplayers: ^5.2.1
  animated_bottom_navigation_bar: ^1.3.3
  cached_network_image: ^3.4.0
  cloud_firestore: 5.6.7
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  easy_localization: ^3.0.2
  firebase_core: 3.13.0
  firebase_storage: 12.4.5
  flutter_html: ^3.0.0-beta.2
  flutter_polyline_points: ^2.1.0
  geo: ^0.3.0
  google_fonts: ^6.2.1
  # google_maps_flutter: ^2.9.0
  # google_sign_in: ^6.2.1
  html_unescape: ^2.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  line_icons: ^2.0.3
  package_info_plus: ^8.3.0
  provider: ^6.1.2
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  skeleton_text: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.10
  the_apple_sign_in: ^1.1.1
  fluttertoast: ^8.2.8
  flutter_facebook_auth: ^7.1.0
  flutter_web_browser: ^0.17.1
  # google_mobile_ads: ^4.0.0
  # last_pod_player: ^0.0.5
  flutter_launcher_icons: ^0.13.1
  # rive: ^0.13.20
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  md2_tab_indicator:
    git:
      url: https://github.com/westdabestdb/md2_tab_indicator
  another_carousel_pro:
    git:
      url: https://github.com/iamnabink/another_carousel_pro
      ref: 6bd1b57
  flutter_dotenv: ^5.2.1
  youtube_player_flutter: ^9.0.4
  flutter_form_builder: ^10.0.0
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flr/
    - assets/translations/
    - assets/.env
    - assets/images/logo.png
    

  fonts:

    - family: Muli
      fonts:
        # - asset: fonts/Montserrat-Light.ttf
        #   weight: 400
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 500
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 600
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800


    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900


    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  branding: assets/images/logo.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/splash.png
  branding_dark: assets/images/logo.png

  android_12:
    image: assets/images/splash.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/splash.png
    icon_background_color_dark: "#FFFFFF"

  fullscreen: true
  android: true
  ios: true
  web: false
